travis:
  secure:
    BINSTAR_TOKEN: SFA7D1yZGMEAIKErh5sJoHMjBp1R4fzA2X7PXvGLXanj/I8wsq663+V4IqCsLK9eBt51q+9/2g10oOzscbG4uQ4hA48AE8pqXsiqylxLphP0boA9zF5HoC9KcnJuQB1a1rlfCpFD8Pb4i6+KDNFFett1/DTB9jMD8utPOAAFz88r0c3ZjdhfEHMzClJIfY69KTqzTfKjAE3o2N7t5+GkFWGGHzEfzAaf/Ezhw7SPaag8OLFOWyadO0qAh6OVhMxYWIszZj0/NmUTCrxgpRIlnSR/BQrlQ0ba/dLxBdFi62Q0esvxpe0uXPFIyw5cMpb02Y1ATiJvNTT4+7OgVapCnUMQwPoeqxcwD4GNBOwvtja/HwQ6v46/ZRxdIYA9V2Pz3PWyvL7+P7+XsVrrtMyHMFWPDz2yJMYQPlubuRfKNnuCJQpMw0EX2bzYir7zpS5tiFNlfKuAygO5BmHlym6Hxf1sDDD1CBbQJvFXoWp8bT6HcVWbwbaNuLxyrNdzWZT491+Olga468y+Apj5LE0gY5kNIuTlwHE36XQD9yf/E57+kXz5P8TCL1At71F9Cvhgz4soz1jjHFxxKsoWP+3hZezwt3dkyo2kmk+Wyblrk/30KGy+AxiYbOZ3dTACqwdvnE3ZqosFJhcSQq4owmMj8ZzWHlBeBCE2iUExH0Abpfg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
