travis:
  secure:
    BINSTAR_TOKEN: idHtVPcQ7x/3xMGc4qw0I9kbDy/lKzZAoaj/kSzH/tQnEWtNBC8IthsYkHqbZUBBKrcKImRAHGXz+CpRISKGR0if3WK7mcZk+D3t6ea3SpT60jygZ0OXHMPfgpTtDvLiq9lnHF1OE/aVcWV7L85Xg9wmYHb/myOIhg33Rvp84mNSZwd+xm+X48PUrmEAVjDww06UJXvOe0ome6+3cS7E/Whi7/9ZIS4mSCfCCA6v/XnAlxPhDfBFmzETOw1L3qfmTIHevFtWcrbE24auXqQyPX32Xza9+l212PcE3jlobrHPZhIcbbwuN4dCnxTInJHOTRHdK5pwI1F1CkxAQiBQPlrjfRb/fUcSuNw8YrL8CtkxXjz9RNqUGRUiFCr1lS7lsCDzvHKw3UQzhQtVUc+tX/DLrd9jdglB+EV+OxokkWjk5vv5iC55SSb9AFKRPdLGXoXPxd9xBer/sfRlYaosETf6UgCN4XmzWHr+PQSbN2nUuYOuDtHHlKfkj33iN2XdzTk2zB5o9F1LwZ8/UMOmmUbAz7ANESUterc0VV1aHY1zgvQ75A9yR2BQ3A8ypEfSezDkCg5MdMGxrd2f2bW3NhQf4dP65W7DoXsW0aVjPlnx9PWW2Qk+LCdjyp5IrdVKHGwEb1ZRF02Sjo7FMOFpkN9C0Fr6lKKq7VbpufFAsdY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
